import React, { useState, useEffect, useRef } from "react";
import { Text, Box, useInput } from "ink";
import Spinner from "ink-spinner";
import { GitHubService, CreateIssueResult } from "../github/github-service.js";
import { GitHubUrlParser } from "../lib/github/github-url-parser.js";
import { GradingResult } from "../lib/utils/file-saver.js";
import { HelpFooter } from "./ui/HelpFooter.js";

export interface IssueCreationResults {
  created: Array<{ repoName: string; issueUrl: string }>;
  skipped: Array<{ repoName: string; reason: string }>;
  failed: Array<{ repoName: string; error: string }>;
}

type RepoStatus = "pending" | "creating" | "created" | "failed";

interface RepoProgress {
  repoName: string;
  githubUrl: string;
  status: RepoStatus;
  issueUrl?: string;
  error?: string;
}

interface GitHubIssueCreationProgressProps {
  gradingResults: GradingResult[];
  issueTitle: string;
  githubToken: string;
  onComplete: (results: IssueCreationResults) => void;
}

function formatIssueBody(gradingData: any): string {
  const repoExplained = gradingData?.repo_explained || gradingData?.object?.repo_explained || "No summary available";
  const developerFeedback = gradingData?.developer_feedback || gradingData?.object?.developer_feedback || "No feedback available";

  return `## Summary
${repoExplained}

## Developer Feedback
${developerFeedback}

---
*Generated by CLI Agents Fleet*`;
}

export const GitHubIssueCreationProgress: React.FC<GitHubIssueCreationProgressProps> = ({
  gradingResults,
  issueTitle,
  githubToken,
  onComplete,
}) => {
  const validResults = gradingResults.filter((r) => r.githubUrl && !r.error);

  const [repoProgress, setRepoProgress] = useState<RepoProgress[]>(
    validResults.map((r) => ({
      repoName: r.repositoryName,
      githubUrl: r.githubUrl,
      status: "pending",
    }))
  );
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [scrollOffset, setScrollOffset] = useState(0);
  const [isComplete, setIsComplete] = useState(false);

  const abortControllerRef = useRef<AbortController | null>(null);
  const viewportSize = 10;

  const completedCount = repoProgress.filter(
    (r) => r.status === "created" || r.status === "failed"
  ).length;

  const visibleStartIndex = scrollOffset;
  const visibleEndIndex = Math.min(scrollOffset + viewportSize, repoProgress.length);
  const displayRepos = repoProgress.slice(visibleStartIndex, visibleEndIndex);

  useEffect(() => {
    const createIssues = async () => {
      const abortController = new AbortController();
      abortControllerRef.current = abortController;

      const service = new GitHubService(githubToken);
      const results: IssueCreationResults = {
        created: [],
        skipped: [],
        failed: [],
      };

      for (let i = 0; i < validResults.length; i++) {
        if (abortController.signal.aborted) break;

        const result = validResults[i];
        const repoInfo = GitHubUrlParser.parse(result.githubUrl);

        if (!repoInfo) {
          setRepoProgress((prev) => {
            const updated = [...prev];
            updated[i] = { ...updated[i], status: "failed", error: "Invalid GitHub URL" };
            return updated;
          });
          results.failed.push({ repoName: result.repositoryName, error: "Invalid GitHub URL" });
          continue;
        }

        setRepoProgress((prev) => {
          const updated = [...prev];
          updated[i] = { ...updated[i], status: "creating" };
          return updated;
        });

        const body = formatIssueBody(result.gradingData);
        const issueResult: CreateIssueResult = await service.createIssue(
          repoInfo.owner,
          repoInfo.repo,
          issueTitle,
          body
        );

        if (issueResult.success && issueResult.issueUrl) {
          setRepoProgress((prev) => {
            const updated = [...prev];
            updated[i] = { ...updated[i], status: "created", issueUrl: issueResult.issueUrl };
            return updated;
          });
          results.created.push({ repoName: result.repositoryName, issueUrl: issueResult.issueUrl });
        } else {
          setRepoProgress((prev) => {
            const updated = [...prev];
            updated[i] = { ...updated[i], status: "failed", error: issueResult.error };
            return updated;
          });
          results.failed.push({ repoName: result.repositoryName, error: issueResult.error || "Unknown error" });
        }

        setCurrentIndex(i + 1);

        if (i >= scrollOffset + viewportSize - 2) {
          setScrollOffset(Math.max(0, i - viewportSize + 3));
        }
        setSelectedIndex(i);
      }

      setIsComplete(true);
      onComplete(results);
    };

    if (validResults.length > 0) {
      setRepoProgress((prev) => {
        const updated = [...prev];
        if (updated.length > 0) {
          updated[0].status = "creating";
        }
        return updated;
      });
      createIssues();
    } else {
      setIsComplete(true);
      onComplete({ created: [], skipped: [], failed: [] });
    }

    return () => {
      abortControllerRef.current?.abort();
    };
  }, [validResults.length, issueTitle, githubToken, onComplete]);

  useInput((input, key) => {
    if (key.upArrow) {
      const newIndex = Math.max(0, selectedIndex - 1);
      setSelectedIndex(newIndex);
      if (newIndex < scrollOffset) {
        setScrollOffset(newIndex);
      }
    } else if (key.downArrow) {
      const newIndex = Math.min(repoProgress.length - 1, selectedIndex + 1);
      setSelectedIndex(newIndex);
      if (newIndex >= scrollOffset + viewportSize) {
        setScrollOffset(newIndex - viewportSize + 1);
      }
    }
  });

  const getStatusIcon = (status: RepoStatus): string => {
    switch (status) {
      case "pending":
        return "○";
      case "creating":
        return "◐";
      case "created":
        return "✓";
      case "failed":
        return "✗";
      default:
        return "○";
    }
  };

  const getStatusColor = (status: RepoStatus): string => {
    switch (status) {
      case "pending":
        return "gray";
      case "creating":
        return "cyan";
      case "created":
        return "green";
      case "failed":
        return "red";
      default:
        return "gray";
    }
  };

  const showScrollIndicatorTop = scrollOffset > 0;
  const showScrollIndicatorBottom = visibleEndIndex < repoProgress.length;

  const createdCount = repoProgress.filter((r) => r.status === "created").length;
  const failedCount = repoProgress.filter((r) => r.status === "failed").length;

  return (
    <Box flexDirection="column">
      <Text color="blue" bold>
        Creating GitHub Issues
      </Text>
      <Text dimColor>Title: "{issueTitle}"</Text>
      <Text></Text>

      <Box marginBottom={1}>
        {!isComplete ? (
          <Box>
            <Text color="cyan">
              <Spinner type="dots" />
            </Text>
            <Text>
              {" "}
              Processing: {currentIndex}/{validResults.length} repositories
            </Text>
          </Box>
        ) : (
          <Box flexDirection="column">
            <Text color="green">Complete!</Text>
            <Text>
              <Text color="green">{createdCount} created</Text>
              {failedCount > 0 && <Text color="red">, {failedCount} failed</Text>}
            </Text>
          </Box>
        )}
      </Box>

      {showScrollIndicatorTop && <Text dimColor> ↑ more above</Text>}

      {displayRepos.map((repo, displayIndex) => {
        const actualIndex = visibleStartIndex + displayIndex;
        const isSelected = selectedIndex === actualIndex;

        return (
          <Box key={repo.repoName} flexDirection="column">
            <Box>
              <Text color={isSelected ? "blue" : getStatusColor(repo.status)} bold={isSelected}>
                {getStatusIcon(repo.status)} {repo.repoName}
              </Text>
              {repo.status === "creating" && (
                <Text color="cyan">
                  {" "}
                  <Spinner type="dots" />
                  {" creating issue"}
                </Text>
              )}
            </Box>
            {isSelected && repo.status === "created" && repo.issueUrl && (
              <Text dimColor>   {repo.issueUrl}</Text>
            )}
            {isSelected && repo.status === "failed" && repo.error && (
              <Text color="red" dimColor>
                {"   "}
                {repo.error}
              </Text>
            )}
          </Box>
        );
      })}

      {showScrollIndicatorBottom && <Text dimColor> ↓ more below</Text>}

      <Text></Text>
      <HelpFooter
        hints={[{ keys: "↑/↓", action: "navigate" }]}
      />
    </Box>
  );
};
